### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by samsmeep23**
new version for Burst 1.8.15

### CODE REVIEW

**Comment by aras-p** [comment]
But why? Is there something in that newer version of Burst that is _required_ by the package?

**Comment by samsmeep23** [comment]
It’s just for the new version of burst so that people with new version can easily install the package^^.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Aras Pranckevičius ***@***.***>
Gesendet: Monday, November 4, 2024 3:23:05 PM
An: aras-p/UnityGaussianSplatting ***@***.***>
Cc: Singh Samsmeep ***@***.***>; Author ***@***.***>
Betreff: Re: [aras-p/UnityGaussianSplatting] Update package.json (PR #142)


But why? Is there something in that newer version of Burst that is required by the package?

**Comment by aras-p** [comment]
But they can already do that. The requirements in package's own package.json spells out "which other packages this package absolutely needs". I don't think it absolutely needs this particular version of burst?

**Comment by samsmeep23** [comment]
Yes you are right:):).

________________________________
Von: Aras Pranckevičius ***@***.***>
Gesendet: Montag, 4. November 2024 16:30
An: aras-p/UnityGaussianSplatting ***@***.***>
Cc: Singh Samsmeep ***@***.***>; Author ***@***.***>
Betreff: Re: [aras-p/UnityGaussianSplatting] Update package.json (PR #142)


But they can already do that. The requirements in package's own package.json spells out "which other packages this package absolutely needs". I don't think it absolutely needs this particular version of burst?

**Pull request closed without merging**
